[target.x86_64-unknown-linux-musl]
linker = "/opt/homebrew/bin/x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "/opt/homebrew/bin/aarch64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "/opt/homebrew/bin/x86_64-w64-mingw32-gcc"
