[package]
name = "helloopengl"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.28"
glfw = "0.55"
gl = "0.14"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.33"

# small convenience for error handling (optional)
thiserror = "1.0"
glow = "0.16.0"

