build:
	cargo build
# 	echo "Try and get zero dep"
# 	echo "Opengl with rust (it's like C with GLv2 having an additional indirection)"
# 	ls -lh ./target/debug/helloopengl
# 	./target/debug/helloopengl  
	cargo run mountain.csv